In [1]:
1+1

2

In [2]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv("titanic.csv",usecols=["Cabin","Ticket"])

In [5]:
df.head()

             Ticket Cabin
0         A/5 21171   NaN
1          PC 17599   C85
2  STON/O2. 3101282   NaN
3            113803  C123
4            373450   NaN

In [8]:
df["cabin_numerical"]=df["Cabin"].str.extract('(\d+)')
df["cabin_categorical"]=df["Cabin"].str[0]

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\Aditya\AppData\Local\Temp\ipykernel_19828\1597230230.py:1: SyntaxWarning: invalid escape sequence '\d'
  df["cabin_numerical"]=df["Cabin"].str.extract('(\d+)')

In [9]:
df.head()

             Ticket Cabin cabin_numerical cabin_categorical
0         A/5 21171   NaN             NaN               NaN
1          PC 17599   C85              85                 C
2  STON/O2. 3101282   NaN             NaN               NaN
3            113803  C123             123                 C
4            373450   NaN             NaN               NaN

In [14]:
df["ticket_numerical"]=df["Ticket"].apply(lambda s: s.split()[-1])
df["ticket_numerical"]=pd.to_numeric(df["ticket_numerical"],
                                     errors="coerce",
                                     downcast="integer")


df["ticket_categorical"]=df["Ticket"].apply(lambda s: s.split()[0])
df["ticket_categorical"]=np.where(df["ticket_categorical"].str.isdigit(),np.nan,df["ticket_categorical"])

In [15]:
df.head()

,Ticket,Cabin,cabin_numerical,cabin_categorical,ticket_numerical,ticket_categorical
0,A/5 21171,NaN,NaN,NaN,21171.0,A/5
1,PC 17599,C85,85,C,17599.0,PC
2,STON/O2. 3101282,NaN,NaN,NaN,3101282.0,STON/O2.
3,113803,C123,123,C,113803.0,NaN
4,373450,NaN,NaN,NaN,373450.0,NaN